<?php

/**
 * @file
 * various code snippets for drupal development
 */
/**
 * Implements hook_permission() 
 */
function googleanalytics_custom_perm() {
  return array('administer google analytics');
}
/**
 * Implements hook_menu() 
 */
function googleanalytics_custom_menu() {
  
	$items['admin/settings/custom'] = array(
    'title' => 'Schizophrenia24x7 Spain Custom',
    'description' => 'Schizophrenia24x7 Spain custom settings',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
	
	$items['admin/settings/custom/google-tracking-code'] = array(
    'title' => 'Google Analytics',
    'description' => 'Configure the Google Analytics tracking code.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('googleanalytics_custom_tracking_code'),
    'access arguments' => array('administer google analytics'),
    'type' => MENU_NORMAL_ITEM,
  );
	
  return $items;
 
}
/**
 * menu callback function 
 * Set the google analytics tracking code here
 * ref ticket: ESQUIZOCOM-26
 */
function googleanalytics_custom_tracking_code() { 
	$form['config'] = array(
		'#type' => 'fieldset',
		'#title' =>'Google analytics configuration',
	);
	$form['config']['ga_script'] = array(
		'#type' => 'textarea',
		'#description' =>'provide the google analytics script here',
		'#default_value' => variable_get('ga_script',''),
	);
	return system_settings_form($form);
} 
/**
 * Implementation of hook_preprocess_page
 */
function googleanalytics_custom_preprocess_page(&$variables) {
	$variables['ga_script'] = variable_get('ga_script','<!-- GA NOT SET -->');
}

/*
function googleanalytics_custom_footer($main = 0) {	
	$script = variable_get('ga_script','');
	return $script;
}
*/

function googleanalytics_custom_block($op = 'list', $delta = 0, $edit = array()){
   
   if ($op == 'list') {
    $blocks[0] = array('info' => t('Custom GA block'),
                       'weight' => 0,
                       'status' => 1,
                       'region' => 'footer');

    return $blocks;
  
  } else if ($op == 'configure' && $delta == 0) {
     
 
  } else if ($op == 'save' && $delta == 0) {
    
  
  }  else if ($op == 'view') {

    switch($delta) {
      case 0:
	  $content = NULL;
	   if(isset($_COOKIE['cookie-compliance-user-response']) || isset($_COOKIE['cookie-compliance-link-response'])){
	      $content = variable_get("ga_script","");
		  }
            $block = array('subject' => t('Custom GA block'),
                          'content' => $content   ); 
        break;
      
    }
    return $block;
  }
}
