<?php

/* Implementation of hook_init */
function custom_menu_tweaks_init() {
  
}

/* Implementation of hook_menu */
function custom_menu_tweaks_menu(){
  $items['family-friend'] = array(
    'title' => 'Family &Friend',
    'page callback' => 'custom_tweaks_family',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  $items['meet-people'] = array(
    'title' => 'I meet people with schizophrenia in my job',
    'page callback' => 'custom_meet_people',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  $items['living-schizophrenia'] = array(
    'title' => 'Living with schizophrenia',
    'page callback' => 'custom_living_schizophernia',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  $items['recently-diagnosed'] = array(
    'title' => 'Recently diagnosed',
    'page callback' => 'custom_recently_diagnosed',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  return $items;
}
function custom_tweaks_family(){
return '';
}
function custom_meet_people(){
return '';
}
function custom_living_schizophernia(){
return '';
}
function custom_recently_diagnosed(){
return '';
}
