<?php  
function custom_schizo_survey_perm() {
  return array('access survey');
}

function custom_schizo_survey_menu(){
 
 $items = array();
  $items['admin/settings/survey_settings'] = array(
    'title' => t('Survey Settings'),
    'page callback' => 'drupal_get_form',
     'page arguments'   => array('survey_admin_settings'),
    'access arguments' => array('access survey'),
    'type' => MENU_NORMAL_ITEM
  );
  
  return $items;
}

function survey_admin_settings(){
 
 $form = array();
 
    $form['visitor_tracker'] = array(
    '#type' => 'fieldset',
    '#title' => t('visitor Tracker Settings'),
  ); 
  
    $form['visitor_tracker']['url'] = array(
    '#type' => 'textfield',
    '#title' => t('Tracker url'),
    '#default_value' => variable_get('url', ''),
    '#size' => 50,
    '#description' => t('Enter the tracker url'),
  );
    
    $form['visitor_tracker']['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Popup Height'),
    '#default_value' => variable_get('height', ''),
    '#size' => 50,
    '#description' => t('Enter the height of the survey'),
  );
    
    $form['visitor_tracker']['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Popup width'),
    '#default_value' => variable_get('width', ''),
    '#size' => 50,
    '#description' => t('Enter the width of the survey'),
  );   
    
/*

  $total_option_color = 1;  
        // Default 15 colors mentioned in the LibChart class file.
        $defult10_color = array('0,0,0','2, 78, 0','148, 170, 36','233, 191, 49','240, 127, 41','243, 63, 34','190, 71, 47','135, 81, 60','128, 78, 162','121, 75, 255','142, 165, 250','162, 254, 239','137, 240, 166','104, 221, 71','98, 174, 35','93, 129, 1');
        for( $option_count = 1; $option_count <= $total_option_color; $option_count++ ) {
            $existing_color = variable_get('background', rgb2html($defult10_color[$option_count]));
            $existing_color = $existing_color == '' ? rgb2html($defult10_color[$option_count]):$existing_color;

            $form['visitor_tracker']['background'] = array(
                '#type' => 'textfield',
                '#description' => t("Click the text box to choose color for survey popup"),
                '#title' => t('Popup background '),
                '#id' => 'chart_color_option_'.$option_count,
                '#size' => 10,
                '#maxlength' => 7,
                '#default_value' => $existing_color,
                '#suffix' =>'<div id=\'picker_'.$option_count.'\'></div>',
                '#attributes' => array('onClick'=>'load_color_picker(\''.$option_count.'\');', 'style'=>'background-color:'.$existing_color),
            );
            
    }
    
*/
 
return system_settings_form($form); 
}


function visitor_tracker_block(){
    
      $url = variable_get('url', '');
      $height = variable_get('height', '');
      $width = variable_get('width', '');
      $background = variable_get('background', '');

//$path = drupal_get_path('module', 'custom_schizo_survey') . '/stophepcdrupal.js';
//$csspath = drupal_get_path('module', 'custom_schizo_survey') . '/ui.all.css';
//$output .= '<link type="text/css" rel="stylesheet" media="all" href="'.$csspath.'"/>';
//$output = drupal_add_js(drupal_get_path('module', 'custom_schizo_survey') . '/citsurvey.js');
$output .= '<script type="text/javascript" src="http://www.a-cross.com/cit2012/survey-jquery-1on3.js"></script>';
$output .= '<script type="text/javascript"> var cit_goals = [];

 loadSurvy("'.$url.'",3,0,2,"citve_v1",'.$width.','.$height.',0.4,"rightabove","#ECEEEF","#000000", cit_goals); </script>';
//print $output;
return $output;
}

/*
* hook_block()
*/

function custom_schizo_survey_block($op = 'list', $delta = 0, $edit = array()){
   
   if ($op == 'list') {
    $blocks[0] = array('info' => t('visitor tracking block'),
                       'weight' => 0,
                       'status' => 1,
                       'region' => 'footer');

    return $blocks;
  
  } else if ($op == 'configure' && $delta == 0) {
     
 
  } else if ($op == 'save' && $delta == 0) {
    
  
  }  else if ($op == 'view') {

    switch($delta) {
      case 0:
            $block = array('subject' => t('visitor tracking block'),
                          'content' => visitor_tracker_block()   ); 
        break;
      
    }
    return $block;
  }
}

