<?php

$pear_icons = array (
	'add' 			=> 'actions/list-add.png',
	'remove' 		=> 'actions/list-remove.png',
	'search'		=> 'actions/search.png',
	'installer'		=> 'system/installer.png',
	'preferences'	=> 'categories/preferences-system.png',
	'readonly'		=> 'emblems/emblem-readonly.png',
	'unreadable'	=> 'emblems/emblem-unreadable.png',
	'package'		=> 'mimetypes/package-x-generic.png',
	'folder'		=> 'places/folder.png',
	'folder-remote'	=> 'places/folder-remote.png',
	'channel'		=> 'places/network-server.png',
	'channels'		=> 'places/network-workgroup.png',
	'error'			=> 'status/dialog-error.png',
	'information'	=> 'status/dialog-information.png',
	'warning'		=> 'status/dialog-warning.png',
	'update'		=> 'status/software-update-available.png',
	'urgent'		=> 'status/software-update-available.png',
);