<?php

/**
* A call back menu for the url website/emailformat
*/
function doctors_net_uk_init(){
	if(!variable_get('dnkuk_user_logged_in' , '')){
		variable_set('dnkuk_user_logged_in',0);
	}
}

function doctors_net_uk_menu(){
	$items = array();
	
	$items['dnuk_user_login'] = array(
			'title' => t('Login DNUK user'),
			'page callback' => 'doctors_net_uk_login_user',
			'type' => MENU_CALLBACK,
			'access callback' => TRUE,
	);
	
	return $items;
}

function doctors_net_uk_preprocess_page(&$vars) {

	drupal_add_js(drupal_get_path('module', 'doctors_net_uk').'/js/jQuery.min.js');
	drupal_add_js(drupal_get_path('module', 'doctors_net_uk').'/js/jQuery.migrate.js');
	drupal_add_js(drupal_get_path('module', 'doctors_net_uk').'/js/jquery.blockUI.js');
	$js = drupal_add_js();
	$vars['scripts'] = drupal_get_js('header', $js);
}

function doctors_net_uk_login_user(){
	global $user;
	$status = 0;
	if($user->uid==0){
		$params = array(
			'name' => 'dnukuser',
			'pass' => 'dnukuser',
		);
		// Authenticate user
		$_REQUEST['destination']='node';
		$account = user_authenticate($params);
		$status = 1;
	}
	variable_set('dnkuk_user_logged_in',1);
	$response = array('status'=>$status);
	echo json_encode($response);
}